movies/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.MovieView.as_view(), name="home"),
    path("filter/", views.FilterMovieView.as_view(), name="filter"),
    path("search/", views.Search.as_view(), name="search"),
    path("about/", views.About.as_view(), name="about"),
    path("json-filter/", views.JsonFilterMoviesViews.as_view(), name="json_filter"),
    path("add_rating/", views.AddStarRating.as_view(), name="add_rating"),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),
]

simple_movie/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include('contact.urls')),
    path("", include("movies.urls"))
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from datetime import date

from django.db import models
from django.urls import reverse




class Category(models.Model):
    name = models.CharField("Назва", max_length=150)
    description = models.TextField("Опис")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"


class Actor(models.Model):
    name = models.CharField("Iм'я", max_length=100)
    age = models.PositiveSmallIntegerField("Вiк", default=0)
    description = models.TextField("Опис")
    image = models.ImageField("Зображення", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актор або Режисер"
        verbose_name_plural = "Актори або Режисери"


class Genre(models.Model):
    name = models.CharField("Назва", max_length=100)
    description = models.TextField("Опис")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанри"


class Movie(models.Model):
    title = models.CharField("Назва", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default="")
    description = models.TextField("Опис")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата виходу", default=2023)
    country = models.CharField("Країна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="Режисер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="Актори", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="Жанри")
    world_premiere = models.DateField("Прем'єра у світі", default=date.today)
    budget = models.PositiveIntegerField(
        "Бюджет", default=0, help_text="Вказувати сумму в $")
    fees_in_usa = models.PositiveIntegerField(
        "Збори в США", default=0, help_text="Вказувати сумму в $")
    fees_in_world = models.PositiveIntegerField(
        "Збори в свiтi", default=0, help_text="Вказувати сумму в $")
    category = models.ForeignKey(
        Category, verbose_name="Категорія", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Чернетка", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={"slug": self.url})

    def get_reviews(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фільм"
        verbose_name_plural = "Фільми"


class MovieShots(models.Model):
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Опис")
    image = models.ImageField("Зображення", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фільм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадри з фільму"
        verbose_name_plural = "Кадри з фільму"


class RatingStar(models.Model):
    value = models.SmallIntegerField("Значення", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Зірка рейтингу"
        verbose_name_plural = "Зірки рейтингу"
        ordering = ["-value"]


class Rating(models.Model):
    ip = models.CharField("IP адресса", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="зiрка")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фiльм")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField("Iм'я", max_length=100)
    text = models.TextField("Текст", max_length=5000)
    parent = models.ForeignKey(
        "self", verbose_name="Посилання", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="Фiльм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Відгук"
        verbose_name_plural = "Відгуки"

movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Reviews, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border"}),
            "email": forms.EmailInput(attrs={"class": "form-control border"}),
            "text": forms.Textarea(attrs={"class": "form-control border", "id": "contactcomment"})
        }


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ('star',)

movies/views.py
from django.contrib.flatpages.views import flatpage
from django.db.models import Q, Avg, Subquery, OuterRef, IntegerField, Value
from django.db.models.functions import Cast, Coalesce
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from django.views.generic.base import View

from .models import Movie, Category, Actor, Genre, Rating
from .forms import ReviewForm, RatingForm


class GenreYear:

    def get_genres(self):
        return Genre.objects.all().order_by('name')

    def get_years(self):
        return Movie.objects.filter(draft=False).values('year').distinct().order_by('-year')


class About(View):
    def get(self, request):
        return flatpage(request, "/about/")


class MovieView(GenreYear, ListView):
    model = Movie
    queryset = Movie.objects.filter(draft=False).annotate(
        average_rating=Coalesce(
            Cast(
                Subquery(
                    Rating.objects.filter(movie=OuterRef('pk')).values('movie').annotate(
                        avg_rating=Avg('star__value')
                    ).values('avg_rating')[:1],
                ),
                IntegerField()
            ),
            Value(0)
        )
    )
    paginate_by = 6
    template_name = "movies/movies.html"

    # def get(self, request):
    #     movies = Movie.objects.all()
    #     return render(request, 'movies/movies.html', {"movie_list": movies})
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        # for movie in self.object_list:
        #     avg_rating = Rating.objects.filter(movie=movie).aggregate(Avg('star__value'))['star__value__avg']
        #     setattr(movie, 'average_rating', int(avg_rating) if avg_rating is not None else 0)
        context['stars_range'] = range(1, 6)
        context['categories'] = Category.objects.all()
        return context


class MovieDetailView(GenreYear, DetailView):
    model = Movie
    slug_field = 'url'
    template_name = "movies/movie_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        average_rating = Rating.objects.filter(movie=context['movie']).aggregate(Avg('star__value'))['star__value__avg']
        context["star_form"] = RatingForm()
        context["average_rating"] = f'{int(average_rating)}' if average_rating is not None else f'0'
        context["form"] = ReviewForm()
        return context

    # def get(self, request, slug):
    #     movie = Movie.objects.get(url=slug)
    #     return render(request, 'movies/movie_detail.html', {"movie": movie})


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.movie = movie
            form.save()

        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = 'name'


class FilterMovieView(GenreYear, ListView):
    template_name = "movies/movies.html"
    paginate_by = 6

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist('year')) |
            Q(genres__in=self.request.GET.getlist('genre'))
        ).distinct()

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['year'] = ''.join([f"year={x}&" for x in self.request.GET.getlist('year')])
        context['genre'] = ''.join([f"genre={x}&" for x in self.request.GET.getlist('genre')])
        return context


class JsonFilterMoviesViews(ListView):
    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist('year')) |
            Q(genres__in=self.request.GET.getlist('genre')))
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"movies": queryset}, safe=False)


class AddStarRating(View):
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get('movie')),
                defaults={'star_id': int(request.POST.get('star'))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    template_name = "movies/movies.html"
    paginate_by = 6

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = f'q={self.request.GET.get("q")}&'
        return context

templates/movies/actor.html
{% extends 'movies/block/base.html' %}
{% load static %}
{% block titleText %}Детально: {{ actor.name }}{% endblock %}
{% block bannerimg %}bg1{% endblock %}
{% block container %}
            <div class="container py-md-3">
 {% endblock %}
 {% block sidebar %}
            <div class="side-bar col-lg-4">
 {% endblock %}

{% block content %}
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6 mb-md-5">
            <img src="{{ actor.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.title }}
            </h3>
            <h5 class="editContent"></h5>
            <ul>
                <li>
                    <span>
                        <h3 class="shop-sing editContent">
                           {{ actor.name }}
                        </h3>
                    </span>
                </li>
                <li><span><b>Вiк:</b> {{ actor.age }} рокiв</span></li>
            </ul>
        </div>
            <hr>

        <div class="col-md-12">
            <!-- Режисер -->
            {% if actor.film_director.all.count != 0 %}
                <h4 class="editContent"><b>Режисер у фiльмах:</b></h4>
               <div class="row row-cols-1 row-cols-md-3 g-4">
                    {% for movie in actor.film_director.all %}
                        <div class="col-md-3">
                            <div class="card h-100" >
                              <img src="{{ movie.poster.url }}" class=" img-fluid rounded-start" style=" max-height: 250px; overflow: hidden;" alt="{{ movie.title }}">
                              <div class="card-body">
                                <h5 class="text-dark">
                                    <a href="{{ movie.get_absolute_url }} " class="text-decoration-none text-dark">
                                        {{ movie.title }}
                                    </a>
                                </h5>
                              </div>
                            </div>

                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <!-- Актер -->
            {% if actor.film_actor.all.count != 0 %}
                <h4 class="editContent"><b>Актор у фiльмах:</b></h4>

                <div class="row row-cols-1 row-cols-md-3 g-4">
                    {% for movie in actor.film_actor.all %}
                        <div class="col-md-3">
                            <div class="card h-100" >
                              <img src="{{ movie.poster.url }}" class=" img-fluid rounded-start" style=" max-height: 250px; overflow: hidden;" alt="{{ movie.title }}">
                              <div class="card-body">
                                <h5 class="text-dark">
                                    <a href="{{ movie.get_absolute_url }} " class="text-decoration-none text-dark">
                                        {{ movie.title }}
                                    </a>
                                </h5>
                              </div>
                            </div>

                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing editContent">
            Про  {{ actor.name }}
        </h3>
        <p class="editContent" >
            {{ actor.description|safe }}
        </p>
    </div>
</div>

{% endblock %}

templates/movies/base.html
<!DOCTYPE html>
{% load static recaptcha3 %}
<html lang="ru">
<head>
    <title>{% block titleText %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% include 'movies/block/head.html' %}
    {% recaptcha_init %}
    {% recaptcha_ready action_name='homepage' %}
</head>

<body>
    <div id="page" class="page">
     <div class="main-banner bg {% block bannerimg %}{% endblock %}" id="home" >
        {% include 'movies/block/mainBanner.html' %}
     </div>

        <ol class="breadcrumb editContent">
            <li class="breadcrumb-item">
                <a href="index.html" class="editContent">Home</a>
            </li>
            <li class="breadcrumb-item active editContent">Single Page</li>
        </ol>

{#     <section class="ab-info-main py-md-5 py-4 editContent"#}
{#    style="padding-left: 3rem; padding-right: 3rem;">#}
        <div class="container pb-5 pt-2">
{#            <div class="row">#}
        {% block content %}
        {% endblock %}
{#              </div>#}
        </div>
{#    </section>#}

    </div>
{% include 'movies/block/footer.html' %}
{#    <script src="{% static 'js/script.js' %}"></script>#}
{#    <script src="http://twitter.github.com/hogan.js/builds/3.0.1/hogan-3.0.1.js"></script>#}
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>

<script>

    const rating = document.querySelector('form[name=rating]');

rating.addEventListener("change", function(event){
    let data = new FormData(this);
    fetch(`${this.action}`,{
        method: "POST",
        body: data
    })
        .then(response => alert('Рейтинг встановлено'))
        .catch(error => alert('Помилка'))
})

</script>


</body>
</html>

templates/movies/movie_detail.html
{% extends 'movies/block/base.html' %}
{% load static %}
{% block titleText %}Детально: {{ movie.title }}{% endblock %}
{% block bannerimg %}bg1{% endblock %}
{% block container %}
            <div class="container py-md-3">
 {% endblock %}
 {% block sidebar %}
            <div class="side-bar col-lg-4">
 {% endblock %}

{% block content %}
                <div class="left-ads-display col-lg-8">
                    <div class="row">
                        <div class="desc1-left col-md-6">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="desc1-right col-md-6 pl-lg-4">
                            <h2 class="editContent">{{ movie.title }}</h2>
                            <h5 class="editContent"></h5>
                            <ul>
                                <li style="list-style: none"><span><b>Год:</b> {{ movie.year }}</span></li>
                                <li style="list-style: none"><span><b>Страна:</b> {{ movie.country }}</span>
                                </li>
                                <li style="list-style: none"><span><b>Слоган:</b> «{{ movie.tagline }}»</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in movie.directors.all %}
                                       <a href="{{ director.get_absolute_url}}" >
                                            {{ director.name }}
                                       </a>
                                        {% endfor %}
                                    </span></li>
                                <li style="list-style: none"><span><b>Актеры:</b>
                                {% for actor in movie.actors.all %}
                                        <a href="{{ actor.get_absolute_url}}" >
                                            {{ actor.name }}
                                        </a>
                                        {% endfor %}
                                </span></li>
                                <li style="list-style: none"><span><b>Жанр:</b>
                                    {% for genre in movie.genres.all %}
                                        {{ genre.name }}
                                        {% endfor %}</span>
                                </li>
                                <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                                <li style="list-style: none">
                                    <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }}</span></li>
                                <li style="list-style: none"><span><b>Сборы в мире:</b> ${{ movie.fees_in_world }}</span>
                                </li>
                                <li style="list-style: none">
                                <hr>
                                    <form action="{% url 'add_rating' %}" method="post" name="rating">
                                    <b>Рейтинг:</b>
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ movie.id }}" name="movie">
                                    <div class="rating">
                                        {% for k, v in star_form.fields.star.choices %}
                                            {% if v <= average_rating %}
                                                <input id="rating{{ v }}" type="radio" name="star" value="{{ v }}" checked>
                                                <label for="rating{{ v }}" class="star-on"></label>
                                            {% else %}
                                                <input id="rating{{ v }}" type="radio" name="star" value="{{ v }}">
                                                <label for="rating{{ v }}" class="star-off"></label>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                    <span class="editContent">{{ average_rating|default:"5.0" }}</span>
                                </form>
                                </li>
                            </ul>
                        <hr>
                                <div class="share-desc">
                                    <div class="share">
                                        <h4 class="editContent"
                                            style="outline: none; cursor: inherit;">
                                            Share:</h4>
                                        <ul class="w3layouts_social_list list-unstyled">
                                            <li>
                                                <a href="#" class="w3pvt_facebook editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" class="w3pvt_twitter editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" class="w3pvt_dribble editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                        </div>
                    </div>
                    <div class="row sub-para-w3layouts mt-5">

                        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                            О фильме {{ movie.title }}</h3>
                       <p>
                          <div class="row">
                              {% for image in movie.movieshots_set.all %}
                                <div class="col-6 col-md-3 mb-4">
                                  <a href="{{ image.image.url }}" data-lightbox="movie-gallery" data-title="{{ image.description }}">
                                    <img src="{{ image.image.url }}" class="img-fluid img-thumbnail" alt="{{ image.description }}">
                                  </a>
                                </div>
                              {% endfor %}
                            </div>
                        </p>
                        <p class="editContent" style="outline: none; cursor: inherit;">{{ movie.description|safe }}</p>
{#                        <p class="mt-3 italic-blue editContent"#}
{#                           style="outline: none; cursor: inherit;">#}
{#                            <iframe width="560" height="315"#}
{#                                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"#}
{#                                    frameborder="0" allow="accelerometer; autoplay;#}
{#                                                                           encrypted-media; gyroscope; picture-in-picture"#}
{#                                    allowfullscreen>#}
{##}
{#                            </iframe>#}
{#                        </p>#}

                    </div>
                    <hr>
                    <div class="row">
                        <div class="single-form-left">
                            <!-- contact form grid -->
                            <div class="contact-single">
                                <h3 class="editContent">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">{{ movie.reviews_set.count}}</span>Залишити вiдгук</h3>
                                <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                                    {% csrf_token %}
                                    <input type="hidden" name="parent" id="contactparent" value="">
                                    <div class="form-group editContent">
                                        <label for="contactcomment" class="editContent">
                                            Ваш комментар *
                                        </label>
                                        {{ form.text }}
                                    </div>
                                    <div class="d-sm-flex">
                                        <div class="col-sm-6 form-group p-0 editContent">
                                            <label for="contactusername" class="editContent">
                                                Iм'я *
                                            </label>
                                            {{ form.name }}
                                        </div>
                                        <div class="col-sm-6 form-group ml-sm-3 editContent">
                                            <label for="contactemail" class="editContent">
                                                Email *
                                            </label>
                                            {{ form.email }}
                                        </div>
                                        {{ form.captcha }}
                                    </div>
                                    <button type="submit"
                                            class="mt-3 btn btn-success btn-block py-3">Вiдправити
                                    </button>
                                </form>
                            </div>
                            <!--  //contact form grid ends here -->
                        </div>
                        {% for review in movie.get_reviews %}
                        <div class="media py-5">
                            <img src="{% static 'images/te2.jpg' %} " class="mr-3 img-fluid" alt="image">
                            <div class="media-body mt-4">
                                <h5 class="mt-0 editContent">
                                    {{ review.name}}
                                </h5>
                                <p class="mt-2 editContent" >
                                    {{ review.text}}
                                </p>
                                <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Вiдповiсти</a>
                                {% for rew in review.reviews_set.all %}
                                <div class="media mt-5 editContent">
                                    <a class="pr-3" href="#">
                                        <img src="{% static 'images/te1.jpg' %}" class="img-fluid "
                                             alt="image" >
                                    </a>
                                    <div class="media-body">
                                        <h5 class="mt-0 editContent">
                                            {{ rew.name }}
                                        </h5>
                                        <p class="mt-2 editContent">
                                            {{ rew.text }}
                                        </p>
                                    </div>
                                </div>
                                    {% endfor %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
    <script>
    function addReview(name, id)
    {
        document.getElementById('contactparent').value = id;
        document.getElementById('contactcomment').innerText = `${name}, `
    }
    </script>
{% endblock %}

templates/movies/movie_list.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% for movie in movie_list %}
{{ movie.title }}
{% endfor %}
</body>
</html>